"""Deterministic graph, IR, and MicroPython transforms for Pololu workflows.

Only compiler-shaped MicroPython is accepted by ``code_to_ir``. The parser uses
``ast`` for Python structure and ``tokenize`` only for optional Dify metadata
comments, keeping code semantics separate from round-trip identity hints.
"""

from __future__ import annotations

import ast
import hashlib
import io
import json
import tokenize
import uuid
from dataclasses import dataclass
from typing import Any

from pydantic import ValidationError

from core.pololu_micropython.entities import (
    PololuCodeResult,
    PololuDiagnostic,
    PololuGraphResult,
    PololuOperation,
    PololuProgram,
    PololuSourceMapEntry,
    PololuStatement,
    PololuTransformResult,
)
from core.pololu_micropython.validation import validate_program

POLOLU_BLOCK_TYPE = "pololu-action"
CUSTOM_NODE_TYPE = "custom"


@dataclass(frozen=True)
class _StatementMetadata:
    statement_id: str | None = None
    node_id: str | None = None
    operation: str | None = None


def stable_hash(value: object) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def graph_to_ir(graph: dict[str, Any]) -> PololuTransformResult:
    """Compile a supported Dify workflow graph into the transient Pololu IR."""
    diagnostics: list[PololuDiagnostic] = []
    nodes = [node for node in graph.get("nodes", []) if isinstance(node, dict)]
    edges = [edge for edge in graph.get("edges", []) if isinstance(edge, dict)]
    nodes_by_id = {str(node.get("id")): node for node in nodes if node.get("id")}
    start_node = next((node for node in nodes if _node_type(node) == "start"), None)
    if start_node is None:
        diagnostics.append(PololuDiagnostic(message="Pololu workflows require a Start node."))
        return PololuTransformResult(program=PololuProgram(), diagnostics=diagnostics)

    ordered_nodes = _walk_linear_nodes(str(start_node["id"]), nodes_by_id, edges, diagnostics)
    statements: list[PololuStatement] = []
    for node in ordered_nodes:
        node_id = str(node.get("id"))
        node_type = _node_type(node)
        if node_type in {"start", "end"}:
            continue
        if node_type != POLOLU_BLOCK_TYPE:
            diagnostics.append(
                PololuDiagnostic(
                    message=f"Unsupported node type in Pololu robot program: {node_type}",
                    node_id=node_id,
                )
            )
            continue
        data = node.get("data")
        if not isinstance(data, dict):
            diagnostics.append(PololuDiagnostic(message="Pololu node data must be an object.", node_id=node_id))
            continue
        statement = _statement_from_node_data(node_id, data, diagnostics)
        if statement:
            statements.append(statement)

    program = PololuProgram(statements=statements)
    diagnostics.extend(validate_program(program))
    return PololuTransformResult(program=program, diagnostics=diagnostics)


def ir_to_code(program: PololuProgram, graph_hash: str = "") -> PololuCodeResult:
    """Render canonical round-trip MicroPython and source-map metadata from IR."""
    diagnostics = validate_program(program)
    lines: list[str] = [
        "# Generated by Dify Pololu MicroPython compiler.",
        "# Edit only the statements marked with '# dify:statement' for reliable round trips.",
        "from time import sleep",
        "from pololu_3pi_2040_robot import robot",
        "",
        "button_b = robot.ButtonB()",
    ]
    devices = _devices_for_program(program)
    for var_name, ctor in [
        ("motors", "Motors"),
        ("display", "Display"),
        ("yellow_led", "YellowLED"),
        ("rgb_leds", "RGBLEDs"),
        ("buzzer", "Buzzer"),
    ]:
        if var_name in devices:
            lines.append(f"{var_name} = robot.{ctor}()")

    lines.extend(["", "try:", "    while True:", "        if button_b.check():", "            break"])
    source_map: list[PololuSourceMapEntry] = []
    for statement in program.statements:
        metadata = _metadata_comment(statement)
        lines.append(f"        {metadata}")
        start_line = len(lines) + 1
        statement_lines = _statement_to_code(statement)
        lines.extend(f"        {line}" for line in statement_lines)
        source_map.append(
            PololuSourceMapEntry(
                statement_id=statement.statement_id,
                node_id=statement.node_id,
                line_start=start_line,
                line_end=len(lines),
            )
        )

    lines.append("finally:")
    cleanup_lines = _cleanup_lines_for_devices(devices)
    if cleanup_lines:
        lines.extend(f"    {line}" for line in cleanup_lines)
    else:
        lines.append("    pass")

    code = "\n".join(lines) + "\n"
    try:
        ast.parse(code)
    except SyntaxError as exc:
        diagnostics.append(
            PololuDiagnostic(
                message=exc.msg,
                line=exc.lineno,
                column=exc.offset,
            )
        )
    return PololuCodeResult(
        code=code,
        source_map=source_map,
        diagnostics=diagnostics,
        graph_hash=graph_hash,
        ir_hash=stable_hash(program.model_dump(mode="json")),
    )


def code_to_ir(code: str) -> PololuTransformResult:
    """Parse compiler-shaped MicroPython into IR using Python's AST whitelist."""
    diagnostics: list[PololuDiagnostic] = []
    try:
        module = ast.parse(code)
    except SyntaxError as exc:
        return PololuTransformResult(
            program=PololuProgram(),
            diagnostics=[
                PololuDiagnostic(
                    message=exc.msg,
                    line=exc.lineno,
                    column=exc.offset,
                )
            ],
        )

    metadata_by_line = _metadata_comments(code)
    _validate_top_level(module, diagnostics)
    try_node = next((stmt for stmt in module.body if isinstance(stmt, ast.Try)), None)
    if try_node is None:
        diagnostics.append(PololuDiagnostic(message="Expected canonical try/finally program structure."))
        return PololuTransformResult(program=PololuProgram(), diagnostics=diagnostics)
    if try_node.handlers or try_node.orelse:
        diagnostics.append(
            PololuDiagnostic(
                message="Exception handlers are not supported in Pololu round-trip code.",
                line=try_node.lineno,
            )
        )

    while_node = next((stmt for stmt in try_node.body if isinstance(stmt, ast.While)), None)
    if while_node is None or not _is_true_constant(while_node.test):
        diagnostics.append(PololuDiagnostic(message="Expected 'while True' robot control loop."))
        return PololuTransformResult(program=PololuProgram(), diagnostics=diagnostics)
    if not while_node.body or not _is_button_b_exit(while_node.body[0]):
        diagnostics.append(PololuDiagnostic(message="Expected Button B exit guard at the start of the loop."))
        return PololuTransformResult(program=PololuProgram(), diagnostics=diagnostics)

    statements: list[PololuStatement] = []
    body = while_node.body[1:]
    index = 0
    while index < len(body):
        parsed_statement, consumed = _parse_statement(body, index, metadata_by_line, diagnostics)
        if parsed_statement:
            statements.append(parsed_statement)
        index += max(consumed, 1)

    program = PololuProgram(statements=statements)
    diagnostics.extend(validate_program(program))
    if (
        any(statement.operation == PololuOperation.SET_MOTORS for statement in statements)
        and not _finally_stops_motors(try_node)
    ):
        diagnostics.append(PololuDiagnostic(message="Motor programs must stop motors in the finally block."))
    diagnostics.extend(_validate_finally_cleanup(try_node))
    return PololuTransformResult(program=program, diagnostics=diagnostics)


def ir_to_graph(program: PololuProgram) -> PololuGraphResult:
    """Render a linear Dify workflow graph from Pololu IR statements."""
    nodes: list[dict[str, Any]] = [_node("start", "start", "User Input", {"variables": []}, 80, 282)]
    previous_id = "start"
    edges: list[dict[str, Any]] = []
    for index, statement in enumerate(program.statements, start=1):
        node_id = statement.node_id or f"pololu-{index}-{statement.statement_id[:8]}"
        node = _node(
            node_id,
            POLOLU_BLOCK_TYPE,
            _title_for_operation(statement.operation),
            {
                "operation": statement.operation.value,
                "parameters": statement.parameters,
                "statement_id": statement.statement_id,
            },
            80 + index * 300,
            282,
        )
        nodes.append(node)
        edges.append(_edge(previous_id, node_id, _node_type(nodes[-2]), POLOLU_BLOCK_TYPE))
        previous_id = node_id

    end_id = "end"
    nodes.append(_node(end_id, "end", "Output", {"outputs": []}, 80 + (len(program.statements) + 1) * 300, 282))
    edges.append(_edge(previous_id, end_id, _node_type(nodes[-2]), "end"))
    graph = {"nodes": nodes, "edges": edges, "viewport": {"x": 0, "y": 0, "zoom": 1}}
    return PololuGraphResult(
        graph=graph,
        diagnostics=validate_program(program),
        ir_hash=stable_hash(program.model_dump(mode="json")),
    )


def strip_round_trip_metadata(code: str) -> str:
    """Remove Dify-only statement comments from code intended for robot export."""
    lines = [line for line in code.splitlines() if not line.strip().startswith("# dify:")]
    return "\n".join(lines) + "\n"


def default_graph() -> dict[str, Any]:
    """Return the starter Pololu graph used for newly created projects."""
    statements = [
        PololuStatement(
            statement_id=_new_statement_id(),
            node_id="pololu-set-motors",
            operation=PololuOperation.SET_MOTORS,
            parameters={"left": 1000, "right": 1000},
        ),
        PololuStatement(
            statement_id=_new_statement_id(),
            node_id="pololu-wait",
            operation=PololuOperation.WAIT,
            parameters={"seconds": 1.0},
        ),
        PololuStatement(
            statement_id=_new_statement_id(),
            node_id="pololu-stop",
            operation=PololuOperation.STOP_MOTORS,
        ),
    ]
    return ir_to_graph(PololuProgram(statements=statements)).graph


def default_features() -> dict[str, Any]:
    """Return the workflow features profile that marks a draft as Pololu-specific."""
    return {
        "retriever_resource": {"enabled": True},
        "pololu_micropython": {
            "enabled": True,
            "schema_version": 1,
            "target": "pololu_3pi_2040",
            "round_trip_version": 1,
            "llm": {
                "provider": "langgenius/openai_api_compatible/openai_api_compatible",
                "model": "qwen3-coder-30b-a3b-instruct",
                "base_url": "https://openai.rc.asu.edu/v1",
            },
        },
    }


def _walk_linear_nodes(
    start_id: str,
    nodes_by_id: dict[str, dict[str, Any]],
    edges: list[dict[str, Any]],
    diagnostics: list[PololuDiagnostic],
) -> list[dict[str, Any]]:
    outgoing: dict[str, list[dict[str, Any]]] = {}
    for edge in edges:
        source = edge.get("source")
        if isinstance(source, str):
            outgoing.setdefault(source, []).append(edge)

    ordered: list[dict[str, Any]] = []
    seen: set[str] = set()
    current_id: str | None = start_id
    while current_id:
        if current_id in seen:
            diagnostics.append(PololuDiagnostic(message="Pololu v1 supports only linear workflows, not graph cycles."))
            break
        seen.add(current_id)
        node = nodes_by_id.get(current_id)
        if node is None:
            diagnostics.append(PololuDiagnostic(message=f"Workflow edge points to missing node: {current_id}"))
            break
        ordered.append(node)
        next_edges = sorted(outgoing.get(current_id, []), key=lambda item: str(item.get("id", "")))
        if len(next_edges) > 1:
            diagnostics.append(
                PololuDiagnostic(message="Pololu v1 supports only one outgoing edge per robot-control node.")
            )
        next_edge = next_edges[0] if next_edges else None
        current_id = str(next_edge.get("target")) if next_edge and next_edge.get("target") else None
    return ordered


def _node_type(node: dict[str, Any]) -> str:
    data = node.get("data")
    if not isinstance(data, dict):
        return ""
    value = data.get("type")
    return str(value) if value is not None else ""


def _statement_from_node_data(
    node_id: str,
    data: dict[str, Any],
    diagnostics: list[PololuDiagnostic],
) -> PololuStatement | None:
    try:
        operation = PololuOperation(str(data.get("operation")))
    except ValueError:
        diagnostics.append(PololuDiagnostic(message="Unsupported Pololu operation.", node_id=node_id))
        return None

    parameters = data.get("parameters")
    if parameters is None:
        parameters = {}
    if not isinstance(parameters, dict):
        diagnostics.append(PololuDiagnostic(message="Pololu operation parameters must be an object.", node_id=node_id))
        return None
    statement_id = data.get("statement_id")
    if not isinstance(statement_id, str) or not statement_id:
        statement_id = _new_statement_id()
    try:
        return PololuStatement(
            statement_id=statement_id,
            node_id=node_id,
            operation=operation,
            parameters=parameters,
        )
    except ValidationError as exc:
        diagnostics.append(PololuDiagnostic(message=str(exc), node_id=node_id))
        return None


def _statement_to_code(statement: PololuStatement) -> list[str]:
    params = statement.parameters
    match statement.operation:
        case PololuOperation.SET_MOTORS:
            return [f"motors.set_speeds({int(params.get('left', 0))}, {int(params.get('right', 0))})"]
        case PololuOperation.STOP_MOTORS:
            return ["motors.off()"]
        case PololuOperation.WAIT:
            return [f"sleep({float(params.get('seconds', 0.0)):g})"]
        case PololuOperation.DISPLAY_TEXT:
            text = json.dumps(str(params.get("text", "")))
            x = int(params.get("x", 0))
            y = int(params.get("y", 0))
            return ["display.fill(0)", f"display.text({text}, {x}, {y})", "display.show()"]
        case PololuOperation.YELLOW_LED:
            method = "on" if bool(params.get("on", True)) else "off"
            return [f"yellow_led.{method}()"]
        case PololuOperation.RGB_LED:
            led = int(params.get("led", 0))
            red = int(params.get("red", 0))
            green = int(params.get("green", 0))
            blue = int(params.get("blue", 0))
            return [f"rgb_leds.set({led}, ({red}, {green}, {blue}))", "rgb_leds.show()"]
        case PololuOperation.BUZZER_BEEP:
            return ["buzzer.beep()"]


def _parse_statement(
    body: list[ast.stmt],
    index: int,
    metadata_by_line: dict[int, _StatementMetadata],
    diagnostics: list[PololuDiagnostic],
) -> tuple[PololuStatement | None, int]:
    stmt = body[index]
    metadata = _nearest_metadata(metadata_by_line, getattr(stmt, "lineno", 0))
    statement_id = metadata.statement_id or _new_statement_id()
    node_id = metadata.node_id

    call = _expr_call(stmt)
    if call is None:
        diagnostics.append(_unsupported_stmt_diagnostic(stmt))
        return None, 1

    if _is_method_call(call, "motors", "set_speeds"):
        args = [_literal(arg) for arg in call.args]
        if len(args) != 2 or not all(isinstance(value, int | float) for value in args):
            diagnostics.append(
                PololuDiagnostic(
                    message="motors.set_speeds requires numeric left and right speeds.",
                    line=stmt.lineno,
                )
            )
            return None, 1
        return (
            PololuStatement(
                statement_id=statement_id,
                node_id=node_id,
                operation=PololuOperation.SET_MOTORS,
                parameters={"left": int(args[0]), "right": int(args[1])},
            ),
            1,
        )
    if _is_method_call(call, "motors", "off"):
        return (
            PololuStatement(statement_id=statement_id, node_id=node_id, operation=PololuOperation.STOP_MOTORS),
            1,
        )
    if _is_name_call(call, "sleep"):
        args = [_literal(arg) for arg in call.args]
        if len(args) != 1 or not isinstance(args[0], int | float):
            diagnostics.append(PololuDiagnostic(message="sleep requires one numeric duration.", line=stmt.lineno))
            return None, 1
        return (
            PololuStatement(
                statement_id=statement_id,
                node_id=node_id,
                operation=PololuOperation.WAIT,
                parameters={"seconds": float(args[0])},
            ),
            1,
        )
    if _is_method_call(call, "yellow_led", "on") or _is_method_call(call, "yellow_led", "off"):
        return (
            PololuStatement(
                statement_id=statement_id,
                node_id=node_id,
                operation=PololuOperation.YELLOW_LED,
                parameters={"on": _is_method_call(call, "yellow_led", "on")},
            ),
            1,
        )
    if _is_method_call(call, "buzzer", "beep"):
        return (
            PololuStatement(statement_id=statement_id, node_id=node_id, operation=PololuOperation.BUZZER_BEEP),
            1,
        )
    display = _parse_display_text(body[index : index + 3], statement_id, node_id)
    if display:
        return display, 3
    rgb = _parse_rgb_led(body[index : index + 2], statement_id, node_id)
    if rgb:
        return rgb, 2

    diagnostics.append(_unsupported_stmt_diagnostic(stmt))
    return None, 1


def _parse_display_text(
    statements: list[ast.stmt],
    statement_id: str,
    node_id: str | None,
) -> PololuStatement | None:
    if len(statements) < 3:
        return None
    fill_call = _expr_call(statements[0])
    text_call = _expr_call(statements[1])
    show_call = _expr_call(statements[2])
    if not (fill_call and text_call and show_call):
        return None
    if not (_is_method_call(fill_call, "display", "fill") and _is_method_call(text_call, "display", "text")):
        return None
    if not _is_method_call(show_call, "display", "show"):
        return None
    args = [_literal(arg) for arg in text_call.args]
    if len(args) < 3 or not isinstance(args[0], str):
        return None
    if not isinstance(args[1], int | float) or not isinstance(args[2], int | float):
        return None
    return PololuStatement(
        statement_id=statement_id,
        node_id=node_id,
        operation=PololuOperation.DISPLAY_TEXT,
        parameters={"text": args[0], "x": int(args[1]), "y": int(args[2])},
    )


def _parse_rgb_led(statements: list[ast.stmt], statement_id: str, node_id: str | None) -> PololuStatement | None:
    if len(statements) < 2:
        return None
    set_call = _expr_call(statements[0])
    show_call = _expr_call(statements[1])
    if not (set_call and show_call):
        return None
    if not (_is_method_call(set_call, "rgb_leds", "set") and _is_method_call(show_call, "rgb_leds", "show")):
        return None
    if len(set_call.args) != 2:
        return None
    led = _literal(set_call.args[0])
    color = _literal(set_call.args[1])
    if (
        not isinstance(led, int)
        or not isinstance(color, tuple)
        or len(color) != 3
        or not all(isinstance(value, int | float) for value in color)
    ):
        return None
    return PololuStatement(
        statement_id=statement_id,
        node_id=node_id,
        operation=PololuOperation.RGB_LED,
        parameters={"led": led, "red": int(color[0]), "green": int(color[1]), "blue": int(color[2])},
    )


def _metadata_comments(code: str) -> dict[int, _StatementMetadata]:
    metadata: dict[int, _StatementMetadata] = {}
    try:
        tokens = tokenize.generate_tokens(io.StringIO(code).readline)
        for token in tokens:
            if token.type != tokenize.COMMENT:
                continue
            text = token.string.strip()
            prefix = "# dify:statement "
            if not text.startswith(prefix):
                continue
            values: dict[str, str] = {}
            for part in text[len(prefix) :].split():
                if "=" not in part:
                    continue
                key, value = part.split("=", 1)
                values[key] = value
            metadata[token.start[0]] = _StatementMetadata(
                statement_id=values.get("id"),
                node_id=values.get("node"),
                operation=values.get("op"),
            )
    except tokenize.TokenError:
        return {}
    return metadata


def _nearest_metadata(metadata_by_line: dict[int, _StatementMetadata], line: int) -> _StatementMetadata:
    candidate_lines = [metadata_line for metadata_line in metadata_by_line if metadata_line < line]
    if not candidate_lines:
        return _StatementMetadata()
    nearest_line = max(candidate_lines)
    if nearest_line != line - 1:
        return _StatementMetadata()
    return metadata_by_line[nearest_line]


def _validate_top_level(module: ast.Module, diagnostics: list[PololuDiagnostic]) -> None:
    for stmt in module.body:
        if isinstance(stmt, ast.ImportFrom):
            if not _allowed_import(stmt):
                diagnostics.append(
                    PololuDiagnostic(message="Unsupported import in Pololu MicroPython program.", line=stmt.lineno)
                )
            continue
        if isinstance(stmt, ast.Assign):
            if not _allowed_device_assignment(stmt):
                diagnostics.append(
                    PololuDiagnostic(message="Unsupported top-level device assignment.", line=stmt.lineno)
                )
            continue
        if isinstance(stmt, ast.Try):
            continue
        if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant) and isinstance(stmt.value.value, str):
            continue
        diagnostics.append(PololuDiagnostic(message="Unsupported top-level Python construct.", line=stmt.lineno))


def _allowed_import(stmt: ast.ImportFrom) -> bool:
    if stmt.module == "time":
        return {alias.name for alias in stmt.names} <= {"sleep"}
    if stmt.module == "pololu_3pi_2040_robot":
        return {alias.name for alias in stmt.names} == {"robot"}
    return False


def _allowed_device_assignment(stmt: ast.Assign) -> bool:
    allowed_constructors = {
        "button_b": "ButtonB",
        "motors": "Motors",
        "display": "Display",
        "yellow_led": "YellowLED",
        "rgb_leds": "RGBLEDs",
        "buzzer": "Buzzer",
    }
    if len(stmt.targets) != 1 or not isinstance(stmt.targets[0], ast.Name):
        return False
    target_name = stmt.targets[0].id
    expected_ctor = allowed_constructors.get(target_name)
    if expected_ctor is None or not isinstance(stmt.value, ast.Call):
        return False
    call = stmt.value
    return _is_method_call(call, "robot", expected_ctor) and not call.args and not call.keywords


def _devices_for_program(program: PololuProgram) -> set[str]:
    devices: set[str] = set()
    for statement in program.statements:
        match statement.operation:
            case PololuOperation.SET_MOTORS | PololuOperation.STOP_MOTORS:
                devices.add("motors")
            case PololuOperation.DISPLAY_TEXT:
                devices.add("display")
            case PololuOperation.YELLOW_LED:
                devices.add("yellow_led")
            case PololuOperation.RGB_LED:
                devices.add("rgb_leds")
            case PololuOperation.BUZZER_BEEP:
                devices.add("buzzer")
            case PololuOperation.WAIT:
                continue
    return devices


def _cleanup_lines_for_devices(devices: set[str]) -> list[str]:
    lines: list[str] = []
    if "motors" in devices:
        lines.append("motors.off()")
    if "yellow_led" in devices:
        lines.append("yellow_led.off()")
    if "rgb_leds" in devices:
        lines.append("rgb_leds.off()")
    if "buzzer" in devices:
        lines.append("buzzer.off()")
    return lines


def _validate_finally_cleanup(try_node: ast.Try) -> list[PololuDiagnostic]:
    diagnostics: list[PololuDiagnostic] = []
    allowed_cleanup_calls = {
        ("motors", "off"),
        ("yellow_led", "off"),
        ("rgb_leds", "off"),
        ("buzzer", "off"),
    }
    for stmt in try_node.finalbody:
        if isinstance(stmt, ast.Pass):
            continue
        call = _expr_call(stmt)
        if call is None:
            diagnostics.append(_unsupported_stmt_diagnostic(stmt))
            continue
        if any(_is_method_call(call, device, method) for device, method in allowed_cleanup_calls):
            continue
        diagnostics.append(_unsupported_stmt_diagnostic(stmt))
    return diagnostics


def _metadata_comment(statement: PololuStatement) -> str:
    parts = [f"id={statement.statement_id}", f"op={statement.operation.value}"]
    if statement.node_id:
        parts.insert(1, f"node={statement.node_id}")
    return "# dify:statement " + " ".join(parts)


def _expr_call(stmt: ast.stmt) -> ast.Call | None:
    if not isinstance(stmt, ast.Expr) or not isinstance(stmt.value, ast.Call):
        return None
    return stmt.value


def _is_method_call(call: ast.Call, name: str, method: str) -> bool:
    return (
        isinstance(call.func, ast.Attribute)
        and call.func.attr == method
        and isinstance(call.func.value, ast.Name)
        and call.func.value.id == name
    )


def _is_name_call(call: ast.Call, name: str) -> bool:
    return isinstance(call.func, ast.Name) and call.func.id == name


def _literal(node: ast.AST) -> Any:
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.UAdd, ast.USub)):
        value = _literal(node.operand)
        if isinstance(value, int | float):
            return value if isinstance(node.op, ast.UAdd) else -value
    if isinstance(node, ast.Tuple):
        return tuple(_literal(item) for item in node.elts)
    return None


def _is_true_constant(node: ast.AST) -> bool:
    return isinstance(node, ast.Constant) and node.value is True


def _is_button_b_exit(stmt: ast.stmt) -> bool:
    if not isinstance(stmt, ast.If):
        return False
    call = stmt.test
    if not isinstance(call, ast.Call) or not _is_method_call(call, "button_b", "check"):
        return False
    return len(stmt.body) == 1 and isinstance(stmt.body[0], ast.Break)


def _finally_stops_motors(try_node: ast.Try) -> bool:
    return any(
        (call := _expr_call(stmt)) is not None and _is_method_call(call, "motors", "off")
        for stmt in try_node.finalbody
    )


def _unsupported_stmt_diagnostic(stmt: ast.stmt) -> PololuDiagnostic:
    return PololuDiagnostic(
        message="Unsupported Python statement in Pololu round-trip subset.",
        line=getattr(stmt, "lineno", None),
        column=getattr(stmt, "col_offset", None),
    )


def _title_for_operation(operation: PololuOperation) -> str:
    return {
        PololuOperation.SET_MOTORS: "Set Motors",
        PololuOperation.STOP_MOTORS: "Stop Motors",
        PololuOperation.WAIT: "Wait",
        PololuOperation.DISPLAY_TEXT: "Display Text",
        PololuOperation.YELLOW_LED: "Yellow LED",
        PololuOperation.RGB_LED: "RGB LED",
        PololuOperation.BUZZER_BEEP: "Buzzer Beep",
    }[operation]


def _node(
    node_id: str,
    block_type: str,
    title: str,
    extra_data: dict[str, Any],
    x: int,
    y: int,
) -> dict[str, Any]:
    return {
        "id": node_id,
        "type": CUSTOM_NODE_TYPE,
        "position": {"x": x, "y": y},
        "targetPosition": "left",
        "sourcePosition": "right",
        "data": {
            "type": block_type,
            "title": title,
            "desc": "",
            **extra_data,
        },
    }


def _edge(source: str, target: str, source_type: str, target_type: str) -> dict[str, Any]:
    return {
        "id": f"edge-{source}-{target}",
        "source": source,
        "target": target,
        "sourceHandle": "source",
        "targetHandle": "target",
        "data": {
            "sourceType": source_type,
            "targetType": target_type,
        },
    }


def _new_statement_id() -> str:
    return str(uuid.uuid4())
